coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 99d63511749ef391db985d7094bce710f115f396
description: tfgnn_v14_ministdlib_py-loader_py-server_ministdlib-166_update-new-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@2b453114a3e0629c2362bb501b5d45f463620f92
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 35e534fa0d66479624b2105648b98daa
model_source_url: http:/64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-01-23_A_v14_ministdlib_py-server_epoch100.35e534fa0d66479624b2105648b98daa.tar.gz
