coq_tactician_commit: 125ec9c1f7e14b62bf9c7f809b4277e2e6055d53
coq_tactician_reinforce_commit: b6594472a547b6f75c3fd8191a5ae7d3b0757b3a
description: tfgnn_v15_stdlib_wip_names_extlib-highschool-100_update-all-defs_tactics128
graph2tac_path: git+https://github.com/IBM/graph2tac.git@0d0a978445f9154695b20f33f257180781a5a525
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --cpu-thread-count 1 --tactic_expand_bound=128
  --total_expand_bound=10 --search_expand_bound=128 --update_all_definitions".
model_md5sum: a5701881ed2affd2e8ba094a3992de57
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-04-14_A_tfgnn_v15_stdlib_v15_names_epoch500.a5701881ed2affd2e8ba094a3992de57.tar.gz
