coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 68e5faa3309c662200444e83d621951556052170
description: 2023-02-27_C_tfgnn_stdlib_main_no-names_high-learning-rate_epoch1
graph2tac_path: git+https://github.com/IBM/graph2tac.git@3fa40ad39ce69422c42e7c1671e848248ab71f81
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-py-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 411bb0fb894fa82040269cd963fba5ad
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-27_C_tfgnn_stdlib_main_no-names_high-learning-rate_epoch1.411bb0fb894fa82040269cd963fba5ad.tar.gz
