coq_tactician_commit: 125ec9c1f7e14b62bf9c7f809b4277e2e6055d53
coq_tactician_reinforce_commit: 10a71ae8973f545de762373846495afe0518c6e5
description: tfgnn_v15_stdlib_v15_names_lr3e-4_extlib-highschool-100_update-all-defs_epoch100S
graph2tac_path: git+https://github.com/LasseBlaauwbroek/graph2tac.git@2bd695e5b2b09b4c972bcd5611ddf27064237cc1
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_all_definitions".
model_md5sum: ce21ed20e09b146b1474729bb333b1c4
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-03-10_A_tfgnn_v15_stdlib_v15_names_lr3e-4_epoch100.ce21ed20e09b146b1474729bb333b1c4.tar.gz
