coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 3190a8fcb4a8c1ea4e6b5d50d85e74842309d3b1
description: 2022-11-22_A_get_jobs_working_better_epoch2
graph2tac_path: git+ssh://git@github.com/IBM/graph2tac.git@ba19130e64ee6ac32451592692c02ed5cf898bd2
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch hmodel --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: eb46b471f40ae903acfa872fd462b129
model_source_url: http:/64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2022-11-22_A_get_jobs_working_better_epoch2.eb46b471f40ae903acfa872fd462b129.tar.gz
