coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 68e5faa3309c662200444e83d621951556052170
description: 2023-02-22_D_tfgnn_stdlib_simplify2-with-cache_names_epoch5
graph2tac_path: git+https://github.com/IBM/graph2tac.git@4604110da3bf61139169b7ac0295a7602e363e30
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-py-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 675a3210a9197b7df0d829ba2ffb18d0
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-22_D_tfgnn_stdlib_simplify2-with-cache_names_epoch5.675a3210a9197b7df0d829ba2ffb18d0.tar.gz
