coq_tactician_commit: 125ec9c1f7e14b62bf9c7f809b4277e2e6055d53
coq_tactician_reinforce_commit: 623952029b0b5e997c08634ba09bb549a0015a0a
description: 2023-07-21_A_tfgnn_v15_stdlib_v15_names-only_epoch110
graph2tac_path: git+https://github.com/IBM/graph2tac.git@e0c278d82b5d06cc2a412edac770ca0b3b3b2237
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-py-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 25c093dabf865d5106840f9b51d6a247
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-07-21_A_tfgnn_v15_stdlib_v15_names-only_epoch110.25c093dabf865d5106840f9b51d6a247.tar.gz
