coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: f6992c129ad99aa47fb80a6322f6ead5e86bda92
description: tfgnn_v13-shared_stdlib_fixed_better-params
graph2tac_path: git+https://github.com/IBM/graph2tac.git@7236c5302ed8f674f895cc14d4df78f1525db489
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 48ddf5b1eced41c060bcfa4e0b2033b5
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2022-12-29_E_tfgnn_v13-shared_stdlib_fixes_better-params_epoch500.48ddf5b1eced41c060bcfa4e0b2033b5.tar.gz
