coq_tactician_commit: 125ec9c1f7e14b62bf9c7f809b4277e2e6055d53
coq_tactician_reinforce_commit: f3337580a26f5ce3dc14432505daba1ec66a5964
description: tfgnn_v15_stdlib_wip_names_extlib-highschool-100_update-all-defs_tactics2048
graph2tac_path: git+https://github.com/IBM/graph2tac.git@ced87e951847111787c62138cfb36c1325d6a2bb
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=2048 --total_expand_bound=10
  --search_expand_bound=2048 --update_all_definitions".
model_md5sum: a5701881ed2affd2e8ba094a3992de57
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-04-14_A_tfgnn_v15_stdlib_v15_names_epoch500.a5701881ed2affd2e8ba094a3992de57.tar.gz
