coq_tactician_api_commit: 51ee26444bf347fddfd6b2408167e617b9b33e8b
coq_tactician_commit: 9224b136ee7823d4776301035d9455f56c8c16b1
description: tfgnn_v15_stdlib_extlib-highschool-100_update-new-defs_knn_max_hidden_learned-embs-for-args_norm-prob-var
graph2tac_path: git+https://github.com/IBM/graph2tac.git@38043ebae3fdb36d0636e3aab6ba598785f0c37d
injection_lines:
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --cpu-thread-count 1 --tactic_expand_bound=256
  --search_expand_bound=256 --update_new_definitions --hard-code-arg-pred-logit-temp
  --knn-proofstep-limit=1000 --knn-duplicate-reduction=max --knn-use-learned-tactic-embeddings-for-arg-prediction
  --knn-keys-ignore-tactic-head --knn-logit-normalize-prob --knn-logit-normalize-var".
model_md5sum: a5701881ed2affd2e8ba094a3992de57
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-04-14_A_tfgnn_v15_stdlib_v15_names_epoch500.a5701881ed2affd2e8ba094a3992de57.tar.gz
