coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 3190a8fcb4a8c1ea4e6b5d50d85e74842309d3b1
description: Test benchmark on one theorem
graph2tac_path: git+ssh://git@github.com/pestun/ibm-graph2tac.git@2878d7cb323fba27951b261388c1df1adc0fdca7
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch hmodel --model %{share}%/%{name}%/model
  --log_level=info --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 5a8c3a58a1e2d34ed32e9400a8cc6088
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2022-09-15_tfgnn_stdlib_main_test.tar.gz
