coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: f6992c129ad99aa47fb80a6322f6ead5e86bda92
description: tfgnn_v13-shared_stdlib_precompute-emb_def-name_stdlib-extlib-highschool-100_update-new-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@b99a366f16bf061518fc692f09dc7b10
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: e8bf2600b8010b6a42d9f3ed399d7c6d
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-01-08_E_tfgnn_v13-shared_stdlib_recompute-emb_no-def-name_epoch68.b99a366f16bf061518fc692f09dc7b10.tar.gz
