coq_tactician_commit: 125ec9c1f7e14b62bf9c7f809b4277e2e6055d53
coq_tactician_reinforce_commit: 10a71ae8973f545de762373846495afe0518c6e5
description: 2023-03-11_B_tfgnn_v15_opam_v15_names_lr3e-4_test_batch32_epoch0
graph2tac_path: git+https://github.com/IBM/graph2tac.git@072848741102e04d26c81217b2d7c5241493f1ed
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-py-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 0e3f44e31f9e31b1fa73a47451ccf3f9
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-03-11_B_tfgnn_v15_opam_v15_names_lr3e-4_test_batch32_epoch0.0e3f44e31f9e31b1fa73a47451ccf3f9.tar.gz
