coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 68e5faa3309c662200444e83d621951556052170
description: 2023-02-21_K_tfgnn_stdlib_shuffle-fix_names_epoch128
graph2tac_path: git+https://github.com/IBM/graph2tac.git@f7de87a7d2b8f4b684cde0f327229c7bde225895
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-py-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: c732aac91fceba7722300fb7b2908fc7
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-21_K_tfgnn_stdlib_shuffle-fix_names_epoch128.c732aac91fceba7722300fb7b2908fc7.tar.gz
