coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 5532831574e0279733501b2bdaa3d4ed09ca0c74
description: tfgnn_v14_stdlib_simplify2_names_extlib-highschool-100_update-all-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@defaf77a3c7b854cbcbb202cecc5a3c53513331b
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_all_definitions".
model_md5sum: 1422689fa8a697430870e817d39c0f62
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-25_D_tfgnn_stdlib_simplify2_names_epoch5.1422689fa8a697430870e817d39c0f62.tar.gz
