coq_tactician_commit: 125ec9c1f7e14b62bf9c7f809b4277e2e6055d53
coq_tactician_reinforce_commit: b6594472a547b6f75c3fd8191a5ae7d3b0757b3a
description: tfgnn_opam-training_main_names_opam-test-170_update-new-defs
graph2tac_path: git+https://github.com/IBM/graph2tac/commit/2c5b88cb2726301fa054cfda4d1730c7d1e3dc3f
injection_lines:
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --cpu-thread-count 1 --tactic_expand_bound=8
  --total_expand_bound=10 --search_expand_bound=100 --update_new_definitions".
model_md5sum: e0e77fe844160530a3e77d31e4fa69d8
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-04-20_B_tfgnn_v15_opam-training_main_names_epoch117.e0e77fe844160530a3e77d31e4fa69d8.tar.gz
