coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: f6992c129ad99aa47fb80a6322f6ead5e86bda92
description: 2023-02-01_A_test_large_shuffle_buffer_epoch0
graph2tac_path: git+https://github.com/IBM/graph2tac.git@247aa3ceb15c96eecf19cf1b5051c7a71a11edc3
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 1fd986ee7175b5e348698f3e38014d6a
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-01_A_test_large_shuffle_buffer_epoch0.1fd986ee7175b5e348698f3e38014d6a.tar.gz
