coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: f6992c129ad99aa47fb80a6322f6ead5e86bda92
description: v13-shared_stdlib_stdlib-hmodel-good-100_update-new-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@266f123229b74443d5267700e3995fc4411aea36
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 31d1376c36c936abf8b8600a4d174a00
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2022-11-04_C_tfgnn_v13-shared_stdlib_epoch500.31d1376c36c936abf8b8600a4d174a00.tar.gz
