coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 3b602e54ff0780e1bdf35af36ccc5ef5b9b8590d
description: v11_stdlib_extlib-highschool-100_update-new-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@ba19130e64ee6ac32451592692c02ed5cf898bd2
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 6d1d973f75daf1bf5d9dfdd362c2f58d
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2022-11-04_D_tfgnn_v11_stdlib_epoch500.6d1d973f75daf1bf5d9dfdd362c2f58d.tar.gz
