coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 68e5faa3309c662200444e83d621951556052170
description: tfgnn_v14_stdlib_main_names_lr3e-4_extlib-highschool-100_update-new-defs_epoch72S
graph2tac_path: git+https://github.com/IBM/graph2tac.git@41dbcd9eb4801d61ecf6cd0620c313a9835e5768
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: fb6b3f6d4ce45b9733d49408cf7bcee9
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-03-08_B_tfgnn_v14_stdlib_main_names_lr3e-4_epoch72.fb6b3f6d4ce45b9733d49408cf7bcee9.tar.gz
