coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 68e5faa3309c662200444e83d621951556052170
description: tfgnn_v14_stdlib_simplify2_names_hmodel-good-100_update-all-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@6b6674883e7b56058f0487b9cc708c71844901bc
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_all_definitions".
model_md5sum: 52d52c1cc9e35b056bbf0f62b667a1f0
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-22_F_tfgnn_stdlib_simplify2_names_epoch145.52d52c1cc9e35b056bbf0f62b667a1f0.tar.gz
