coq_tactician_commit: 43c5badf0d0c272b75c68ca67a49428b2adf0184
coq_tactician_reinforce_commit: e4df10867dbed8e4a03205e6be55cb5fa91128e8
description: tfgnn_opam-training_main_no-def_lr-schedule-20epochs_update-new-defs
graph2tac_path: git+https://github.com/IBM/graph2tac.git@8ba2f1634fb25aeb5da90a4e5840eee964cc0e19
injection_lines:
- Set Tactician Neural Executable "g2t-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --cpu-thread-count 1 --tactic_expand_bound=256
  --search_expand_bound=256".
model_md5sum: 829ca19c47a8f399285c5e3d20fd68ba
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-07-09_A_tfgnn_v15_opam-training_main_no-def_from_start_lr-schedule_20epochs_epoch20.829ca19c47a8f399285c5e3d20fd68ba.tar.gz
