coq_tactician_commit: d46eea21558d382888fc5a25e238af3be31c9a00
coq_tactician_reinforce_commit: 99d63511749ef391db985d7094bce710f115f396
description: 2023-02-02_B_tfgnn_v14_stdlib_py-loader_names_epoch241
graph2tac_path: git+https://github.com/IBM/graph2tac.git@d716a8a6ab9de5a21646c0bdaf4106e7418b9da9
injection_lines:
- Unset Tactician Neural Truncate.
- Set Tactician Neural Executable "g2t-py-server --arch tfgnn --model %{share}%/%{name}%/model
  --log_level=summary --tf_log_level=critical --tactic_expand_bound=8 --total_expand_bound=10
  --search_expand_bound=100 --update_new_definitions".
model_md5sum: 99ed6e0c16abe2bcea276b93e83c2a50
model_source_url: http://64.71.146.254:8000/SFyud_C5TmEq7AwnK9jaLsfTFMzgBl54cQ0pl2FJB-x9o2Hk24F4jO_W75RqGdOJ/weights/2023-02-02_B_tfgnn_v14_stdlib_py-loader_names_epoch241.99ed6e0c16abe2bcea276b93e83c2a50.tar.gz
