#!/usr/bin/env bash
set -ue
python3 -m venv ./venv
. ./venv/bin/activate
pip install git+ssh://git@github.com/IBM/graph2tac.git@d3eb34967874adc41bc57a17a37fe7905278f8d3
pip install tensorflow==2.9
pip install tensorflow-gnn==0.2